= enV5 Base Project
:toc:
:toclevels: 3
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]

toc::[]

== Setup

For compiling the project, the required tools are:

.Prerequisites
- gcc (local C compiler)
- arm-non-eabi-gcc (C compiler for RP2040)
- CMake (Build Script Generator)
- Ninja (Build Tool)

.Local Setup
. Install all required tools (see Prerequisites)
. Clone the repo to your local machine
. Open the project in your preferred C/C++ IDE

[IMPORTANT]
====
You have to adjust the network/mqtt broker credentials as mentioned in the link:https://github.com/es-ude/elastic-ai.runtime.enV5/blob/d862d803a56f0371f9a027b0f304b9ddfa7cd541/src/network/README.adoc[network README]!

Alternatively, you can pass these settings via CMake Flags to the Profile initialization:

- WiFi Name: `-D WIFI_SSID:STRING=<ssid>`
- WiFi Password: `-D WIFI_PWD:STRING=<password>`
- MQTT Host/IP: `-D MQTT_HOST:STRING=<host>`
- MQTT Port: `-D MQTT_PORT:STRING=<port>`
- MQTT Broker User: `-D MQTT_USER:STRING=<user>`
- MQTT Password for User: `-D MQTT_PWD:STRING=<password>`
====

[#_cmake]
== CMake

.CMake Profiles (link:./CMakePresets.json[CMakePresets.json]):
- *ENv5_debug*
- *ENv5_release*

.Configure CMake and Build Target
[source,bash]
----
# configure project
cmake --preset <profile>

# build target
cmake --build --preset <profile>
----

[#_flashing_the_elastic_node_version_5_env5]
==== Flashing the Elastic Node version 5 (enV5)

. Press and hold `MCU BOOT` on the Elastic Node
. Press `MCU RST` on the Elastic Node
. Release `MCU BOOT`
. Copy the `*.uf2` File to the RPI-RP2 device

[#_cmd_line_output]
==== CMD line output

If the pico is connected to the local machine the `printf()` statements inside the code will be redirected to the USB and are available as serial port output.
This output can be read via a serial port reader like screen, minicom or https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html[putty].

The following example shows how to use minicom on a Unix-based system:

[source,bash]
----
minicom \
-b 115200  \ #<1>
-o \ #<2>
-D /dev/ttyACM0 #<3>
----

<1> `-b 115200` -> baud rate for connection
<2> `-o` -> disable modem initialisation
<3> `-D /dev/ttyACM0` -> serial port

[IMPORTANT]
====
The serial port differs depending on the host machine!
It can be found via `ls /dev/tty*` (Linux) or `ls /dev/tty.*` (macOS) from the terminal.
====

[#_debug_output]
==== Debug Output

To enable enhanced Debug output, add the flag `-D DEBUG_OUTPUT:BOOL=ON`
to the <<_cmake,CMake Setup call>> (or add it in the CLion CMake options).
This enables the `PRINT_DEBUG(...)` from the common_lib of the enV5 repository in all targets.

== Project structure

This project contains various folders:

[cols=">,<",options="header"]
|===
|Folder |Description

|link:build[]
|contains all CMake generated build scripts and generated `*.uf2` files

|link:src[]
|contains _Main.c_, helpers and your own source code
|===

